disabled_rules: # rule identifiers to exclude from running
  - force_cast
  - trailing_whitespace 
  - large_tuple
  - cyclomatic_complexity
  - identifier_name
  - type_name
  - multiple_closures_with_trailing_closure
  - nesting
  - syntactic_sugar
  - force_try
  - unused_closure_parameter
  - function_parameter_count
  - empty_parentheses_with_trailing_closure
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  #- Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 
  - 1000
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 500 # error
# or they can set both explicitly

function_body_length:
  - 500 # warning
  - 1000 # error

file_length:
  warning: 1000
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
identifier_name:
  min_length: # only min_length
    warning: 2 # only error
  excluded: # excluded via string array
    - db
    - id
    - h
    - i
    - w
    - x
    - y
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)